### ISSUE TITLE
__init__.py

### ISSUE THREAD

**Issue by Vmansuria** [mecworks/garden_pi#1]
The rcsensor object is not in the ___init__.py_ file. I am trying to recreate only the soil moisture sensor setup with the same sensor and rspberry pi. I receive the following error when I run _soil_sensor.py_: ImportError : cannont import name 'rcensor' from 'common'.

Any reason the object was removed?

**Comment by mecworks** [comment]
@Vmansuria, check out the GPIO sensors branch.  It's located there.  I switched to using an analog sensor in the main branch which is not complete.  The other branch was working and contains the rcsensor.
